server:
  port: 8089

spring:
  application:
    name: car-ware
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost/car-life?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


#mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: not_null
      table-underline: true
logging:
  level:
    com.ware: debug

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'